<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

    <div class="row">
        <div class="col-md-6">
            <?php echo DwForm::hidden('organizacion.territorio_id', NULL, $territorio_id) ?>
            <?php echo DwForm::text('organizacion.nombre', array('class' => 'input-required'), NULL, 'Organización que gestiona el territorio'); ?>
        </div>
        <div class="col-md-3">
            <?php echo DwForm::text('organizacion.sigla', array('class' => ''), NULL, 'Sigla'); ?>
        </div>
        <div class="col-md-3">
            <?php echo DwForm::text('organizacion.integrantes', array('class' => ''), NULL, 'Número integrantes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php echo DwForm::text('organizacion.nombre_representante_legal', array('class' => 'input-required'), NULL, 'Nombre del representante legal'); ?>
            <?php //echo DwForm::dbSelect('organizacion.mads_car_id', 'nombre', array('opcion/mads_car', 'getListadoMadsCarDBS', MadsCar::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Entidad que ejecuta la acción de seguimiento y control');  
            ?>
        </div>
        <div class="col-md-3">
            <?php echo DwForm::date('organizacion.fecha_inicio_representante_legal', array('class' => 'input-required'), '', 'Representante legal desde que fecha'); ?>
        </div>
        <div class="col-md-3">
            <?php echo DwForm::select('organizacion.frecuencia_asamblea', array('' => 'Seleccione', 'CADA AÑO' => 'CADA AÑO', 'CADA 2 AÑOS' => 'CADA 2 AÑOS', 'CADA 3 AÑOS O MAS' => 'CADA 3 AÑOS O MAS'), array('class' => 'input-required'), NULL, 'Frecuencia de la asamblea'); ?>
        </div>
    </div>
    <div class="row">        
        <div class="col-md-6">
            <?php echo DwForm::textarea('organizacion.descripcion', array('class' => 'input-lower'), '', 'Descripción de la estructura de la junta directiva'); ?>
        </div>
        <div class="col-md-6">
            <label for="panel_comite">Seleccione los campos de gestión del territorio</label>
            <div id="panel_comite" class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <?php echo DwForm::dbCheckId('campo_gestion', 'nombre', array('opcion/campo_gestion', 'getCampoGestionDBS'), NULL, NULL, 2, '6'); ?>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <br>
    <div class="row">
    <div class="col-md-6">
            <label for="panel_comite">Seleccione los campos de acción</label>
            <div id="panel_comite" class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">
                        <?php echo DwForm::dbCheckId('campo_accion', 'nombre', array('opcion/campo_accion', 'getCampoAccionDBS'), NULL, NULL, 2, '6'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <label for="panel_fuente">
                <h3 class="panel-title">Fuente(s) de la información</h3>
            </label>

            <div id="panel_fuente" class="panel panel-default">
                <div class="panel-body">
                    <?php View::partial('fuentes/agregar', false, NULL); ?>
                </div>
            </div>
        </div>
    </div>




    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Guardar organizacion'); ?>
            <?php echo DwForm::cancel($url_redir_back); ?>
            <?php //echo DwForm::focus('organizacion.nombre'); 
            ?>
        </div>
    </div>

    <?php echo DwForm::close(); ?>

</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#organizacion_asociacion_organizacion_comunitario_id").on('change', function(e) {
            var data = $('#organizacion_asociacion_organizacion_comunitario_id').val();
            if (data == '') {
                $('#organizacion_pertenece_asociacion_organizacion_comunitario').val('NO');
            } else {
                $('#organizacion_pertenece_asociacion_organizacion_comunitario').val('SI');
            }
        });


        $('#div_organizacion_se_aplica_reglamento').hide();
        $('#div_organizacion_descripcion_aplicacion_reglamento').hide();
        $("#organizacion_tiene_reglamento_interno").on('change', function(e) {
            var data = $('#organizacion_tiene_reglamento_interno').val();
            if (data == 'SI') {
                $('#div_organizacion_se_aplica_reglamento').show();
                $('#organizacion_se_aplica_reglamento').focus();
            } else {
                $('#div_organizacion_se_aplica_reglamento').hide();
                $('#organizacion_se_aplica_reglamento').val('');
                $('#div_organizacion_descripcion_aplicacion_reglamento').hide();
                $('#organizacion_descripcion_aplicacion_reglamento').val('');
            }
        });

        $("#organizacion_se_aplica_reglamento").on('change', function(e) {
            var data = $('#organizacion_se_aplica_reglamento').val();
            if (data == 'SI') {
                $('#div_organizacion_descripcion_aplicacion_reglamento').show();
                $('#organizacion_descripcion_aplicacion_reglamento').focus();
            } else {
                $('#div_organizacion_descripcion_aplicacion_reglamento').hide();
                $('#organizacion_descripcion_aplicacion_reglamento').val('');
            }
        });


    });
</script>