<?php DwForm::open() ?>
               <?php $contador = 1; 
                    $tabla = '';
                    $tabla_identi = '';
              ?>
               <?php foreach($fuentes as $fuente): ?>         
                    <?php echo "<div class='row'>"; ?>                                
                       <?php echo "<div  class='col-md-2'>"; ?>  
              <?php echo DwForm::hidden('fuente.id'.$contador, NULL, $fuente->id); ?>                        
              <?php echo DwForm::date('fuente.fecha'.$contador, array('class'=>'input-required'), date('d-m-Y', strtotime($fuente->fecha)), 'Fecha de la fuente'); ?>                   
              <?php echo "</div> <div class='col-md-9'>"; ?>    
              <?php echo DwForm::text('fuente.nombre'.$contador, array('class'=>'input-lower input-required'), $fuente->nombre, 'Descripción de la fuente'); ?>      
              <?php echo "</div>"; ?>   
              <?php echo "<div class='col-md-1'>"; ?>    

              <?php 
              if(sizeof($fuentes) > 1){
              echo '<div class="form-group"><label for="btn_delete'.$fuente->id.'">&nbsp;</label>';
              echo '<button onclick="setIdBorrar(this.value)" value="'.$fuente->id.'" id="btn_delete'.$fuente->id.'" type="button" class="form-control btn btn-danger btn-xs" data-toggle="modal" data-target="#myModalDelete">';
              echo '<i class="btn-icon-only fa fa-minus"></i></button></div>';
              }
              ?>   

              <?php echo "</div></div>"; ?>
               <?php 
                    $contador++; 
                    $tabla = $fuente->tabla;
                    $tabla_identi = $fuente->tabla_identi;
                ?>
              
                <?php endforeach; ?>
               <input id="fuente_cantidad" name="fuente[cantidad]" type="hidden" value=" <?php echo $contador-1; ?>"> 
               