                 <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">                
                <?php
                    echo DwHtml::button("gestion_territorial/gestion_tcur/agregar_consejo/1/$obj_territorio->id/$obj_territorio->nombre/$key/$order/$page/", 'agregar organización', array('class' => 'btn-success', 'title'=>''), 'fa-check-square-o', APP_AJAX);              
                ?>                   
            </div>            
        </div>
    </div>                   
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th>NOMBRE ORGANIZACIÓN</th>                    
                    <th>REPRESENTANTE LEGAL</th>
                    <th class="btn-actions text-center">ESTADO</th>
                    <th class="btn-actions col-blocked text-center">OPCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $contador_consejo = 1;
                foreach($consejos as $consejo): ?>                    
                    <?php //$key_show = Security::setKey($consejo->id, 'show_consejo'); ?>
                    <?php $key_upd = Security::setKey($consejo->id, 'upd_consejo'); ?>                    
                    <?php $key_del = Security::setKey($consejo->id, 'del_consejo'); ?>                    
                    <tr>
                        <td><?php echo $contador_consejo; ?></td>                        
                        <td><?php echo $consejo->nombre; ?></td>
                        <td><?php echo $consejo->nombre_representante_legal; ?></td>
                        <td class="btn-actions"><?php View::partial('nivel_estado/ver', false, array('nivel'=>$consejo->nivel, 'estado'=>$consejo->estado)); ?>
                        <td class="btn-actions">
                            <?php View::partial('opcion/ver', false, 
                                    array('elemento'=>'consejo',
                                        "nombre"=>$consejo->nombre,
                                        "url_ver"=>NULL,
                                        "url_editar"=>"gestion_territorial/gestion_tcur/editar_consejo/$key_upd/$key/$order/$page/",
                                        "url_eliminar"=>"gestion_territorial/gestion_tcur/eliminar_consejo/$consejo->nombre/$obj_territorio->nombre/$key_del/$key/$order/$page/")); ?>
                        </td>
<!--                        <td class="btn-actions">
                            <?php //echo DwHtml::buttonTable('Ver consejo', "gestion_territorial/gestion_tcur/ver_consejo/$key_show/$key/", null, 'info', 'fa-search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar consejo', "gestion_territorial/gestion_tcur/editar_consejo/$key_upd/$key/$order/$page/", null, 'warning', 'fa-edit'); ?>                            
                        </td>-->
                    </tr>
                    <?php $contador_consejo++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
   <br>