<?php View::flash(); ?>

<div class="container shell-view">

        <?php View::process_estado_nivel('cultivo_ilicito', $cultivo_ilicito, $page_module, $page_title, $set_title); ?>


    <?php echo DwForm::open(); ?>
    
     <ul class="nav nav-tabs nav-justified hidden-xs">
        <li class="<?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="<?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Afectaciones</a></li>       
        <li class="<?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Fuente(s) de la información</a></li>         
    </ul>
    <ul class="nav nav-tabs nav-justified visible-xs">    
        <li class="tab-pane <?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Afectaciones</a></li>        
        <li class="tab-pane <?php echo $tab_3_active; ?>" ><a href="#tab3" data-toggle="tab">Fuente(s) de la información</a></li>        
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane <?php echo $tab_1_active; ?>" id="tab1">
            <div class="row">
            <div class="col-md-12">
            <div class="row">
                <?php View::partial('ubicacion/editar', false, 
                        array('ubicaciones'=>$ubicaciones, 
                            'afectacion_id'=>$cultivo_ilicito->afectacion_id,
                            'titulo'=>'de la política pública')); 
                ?>                          
            </div>
               <!--  <div class="row">
                           <div class="col-md-12">
                               <label for="panel_ubicacion_proyecto"><h3 class="panel-title">Ubicación del cultivo ilícito</h3></label>
                            <div id="panel_ubicacion_proyecto" class="panel panel-default">
                                <div class="panel-body">
                                
                      
                      <div class="row">
                        <div class="col-md-3" id="div_departamento"> 
                            <?php echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS', Departamento::ACTIVO), NULL, array('class'=>'input-required'), $ubicacion->departamento_id, 'Departamento'); ?>                           
                        </div>
                        <div class="col-md-3" id="div_municipio">                    
                            <?php echo DwForm::dbSelect('caso.municipio_id', 'nombre', array('observatorio/municipio', 'getMunicipioPorDepartamento',  $ubicacion->departamento_id), NULL, array('class' => 'input-required'), $ubicacion->municipio_id, 'Municipio'); ?>                        </div>
                       <div class="col-md-6" id="div_territorio">                                                
                           <?php echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', $ubicacion->municipio_id), NULL, array('class' => ''), $ubicacion->territorio_id, 'Territorio'); ?>
                        </div>  
                          
                </div>
                      
                                </div>
                            </div>                           
                        </div>                          
                      </div> -->
                <div class="row">
                    <div class="col-md-3">
                        <?php echo DwForm::hidden('cultivo_ilicito.afectacion_id', NULL, NULL) ?>
                        <?php echo DwForm::dbSelect('cultivo_ilicito.tipo_cultivo_id', 'nombre', array('opcion/tipo_cultivo', 'getListadoTipoCultivoDBS', ''), NULL, array('class'=>'input-required'), NULL, 'Seleccione el tipo de cultivo'); ?>
                    </div>                            
                    <div class="col-md-3">
                            <label for="area">Área del cultivo<!--<span class="req">*</span>--></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input value="<?php echo number_format($cultivo_ilicito->area, 2, '.', ','); ?>" id="area" name="cultivo_ilicito[area]" type="text" class="form-control formato_punto_coma" required="" data-invalid="">                                          
                                          <div class="input-group-addon">hectareas</div>                                          
                                        </div>
                                      </div>
                        </div>
                     
                     <div class="col-md-6">
                 <label for="panel_promotores">Promotores del cultivo</label>   
                <div id="panel_promotores" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_guerrilla', '1', NULL, NULL, 'GUERRILLA'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_paramilitar', '1', NULL, NULL, 'PARAMILITARES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.promo_otro', '1', NULL, NULL, 'OTROS'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>
            

                </div>    
                <div class="row">
                    <div class="col-md-12">
                        <label for="panel_participacion"><h3 class="panel-title">Participación en el cultivo</h3></label>   
                <div id="panel_participacion" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">

                                          
                               <div class="col-md-4">  
                                    <?php echo DwForm::select('cultivo_ilicito.part_comunidad', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿La comunidad participa en el cultivo?'); ?>
                               </div>
                            
                            
                                
                                <div id="div_tipo_part_comunidad" class="col-md-4">
                 <label for="panel_tipo_part_comunidad">Tipo de participación de la comunidad</label>   
                <div id="panel_tipo_part_comunidad" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_cultivador', '1', NULL, NULL, 'CULTIVADORES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_raspachin', '1', NULL, NULL, 'RASPACHINES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_com_procesador', '1', NULL, NULL, 'PROCESADORES'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>
                                
                       </div> 
                                                    
                      
                           
                           
                           <!-- ------------------------------ -->
                           
                            <div class="row">
                               <div class="col-md-4">  
                                    <?php echo DwForm::select('cultivo_ilicito.part_otro', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, '¿Otros participan en el cultivo?'); ?>
                               </div>
                           
                                <div id="div_tipo_part_otro" class="col-md-4">
                 <label for="panel_tipo_part_otro">Tipo de participación de otros</label>   
                <div id="panel_tipo_part_otro" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_cultivador', '1', NULL, NULL, 'CULTIVADORES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_raspachin', '1', NULL, NULL, 'RASPACHINES'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::check('cultivo_ilicito.tipo_part_otr_procesador', '1', NULL, NULL, 'PROCESADORES'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
            </div>       
                                
                                <div id="div_part_otro_quien" class="col-md-4">
                                   <?php echo DwForm::textarea('cultivo_ilicito.part_otro_quien', array('class'=>'input-lower'), NULL, '¿Quienes son los otros participantes?'); ?>
                                </div>                                 
                               
            </div>                                                                                  
        
                           
                           
                           
                           
                           
                           
                    </div>                                        
                  </div>
               </div>
            </div>
                
                <label for="panel_erradicacion"><h3 class="panel-title">Erradicación</h3></label>                
               <div id="panel_erradicacion" class="panel panel-default">
                  <div class="panel-body">
                   <div class="row">
                     <div class="col-md-6">  
                        <?php echo DwForm::select('cultivo_ilicito.tipo_erradicacion', array(''=>'Seleccione', 'ASPERSION AEREA'=>'ASPERSIÓN AÉREA', 'ERRADICACION MANUAL'=>'ERRADICACIÓN MANUAL'), array('class'=>''), NULL, 'Tipo de erradicación'); ?>
                    </div>  
                       <div class="col-md-6">
                            <label for="area_erradicacion">Área<!--<span class="req">*</span>--></label>
                                     <div class="form-group">
                                        <div class="input-group">                                 
                                            <input value="<?php echo number_format($cultivo_ilicito->area_erradicacion, 2, '.', ','); ?>" id="area_erradicacion" name="cultivo_ilicito[area_erradicacion]" type="text" class="form-control formato_punto_coma" required="" data-invalid="">                                          
                                          <div class="input-group-addon">hectareas</div>                                          
                                        </div>
                                      </div>
                        </div>
                </div>
                      <div class="row"> 
                          <div class="col-md-6">
                <label for="panel_modalidad">Modalidad</label>   
                <div id="panel_modalidad" class="panel panel-default">
                  <div class="panel-body">
                       <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::select('cultivo_ilicito.ejecucion_directa', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Ejecución directa'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php echo DwForm::select('cultivo_ilicito.contratada', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Contratada'); ?>
                                </div>
                            </div>
                            <div class="row">
                                <div id="div_contratada_quienes" class="col-md-12">
                                    <?php echo DwForm::textarea('cultivo_ilicito.contratada_quienes', array('class'=>'input-lower'), NULL, '¿Quienes fueron contratados?'); ?>
                                </div>
                            </div>                              
                        </div>                 
                    </div>                                        
                  </div>
               </div>
                          </div>
                      <div class="col-md-6">
                          <?php echo DwForm::select('cultivo_ilicito.consulta_previa', array(''=>'Seleccione', 'SI'=>'SI', 'NO'=>'NO'), array('class'=>''), NULL, 'Consulta previa'); ?>
                      </div>
                      </div>                     
                                           
                  </div>
               </div>
            </div>
               
        </div>                        
             <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Actualizar Cultivo Ilícito'); ?>
                <?php echo DwForm::cancel('afectacion/cultivo_ilicito/listar/'); ?>
                <?php //echo DwForm::focus('caso.titulo'); ?>
            </div>
        </div>
        </div>
                        
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
<div class="tab-pane <?php echo $tab_2_active; ?>" id="tab2">  
<div class="row">
        <div class="col-md-12">                
<div class="row"> 
    <div class="modal fade" id="modal-agregar-dano">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar daño</h4>
                </div>
                <div class="modal-body">
                    <div class="row">  
                        <div class="col-md-12">
                            <?php echo DwForm::dbSelect('afectacion_dano_territorio.territorio_id', 'nombre', array('observatorio/territorio', 'getListadoTerritoriosDBS', NULL), NULL, array('class' => '', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Territorio afectado<span class="req">*</span>'); ?>
                            <?php echo DwForm::dbSelect('afectacion_dano_territorio.tipo_dano_id', 'nombre', array('opcion/tipo_dano', 'getListadoTipoDanoDBS', NULL), NULL, array('class' => '', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Tipo de daño<span class="req">*</span>'); ?>
                            <div id="div_select_dano">
                                <?php echo DwForm::dbSelect('caso_dano_territorio.dano_id', 'nombre', array('opcion/dano', 'getDanoByTipoDanoIdDBS', NULL), NULL, array('class'=>'', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Daño<span class="req">*</span>'); ?>
                            </div>
                            <?php echo DwForm::textarea('afectacion_dano_territorio.descripcion', array('class'=>'input-lower', 'onkeyup'=>'validarBotonAgregarDano()', 'style'=>"height: 130px;"), NULL, 'Descripción del daño<span class="req">*</span>'); ?>
                            
                        </div>                       
                    </div>                                   
                </div>
                <div class="modal-footer">
                    <button id="btn-cancelar-agregar-dano" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-agregar-dano" type="button" class="btn btn-primary" onclick="agregarDano()" data-loading-text="Agregando...">Agregar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <label for="panel_danos"></label>
</div>  
    <div class="container-overflow">
        <button style="margin-bottom: 5px;" id="btn-agregar" type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-agregar-dano" onclick="deshabilitar_modal_dano()" >Agregar daño</button>
        <div id="div_gestion_danos">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>TERRITORIO</th>
                    <th>TIPO DE DAÑO</th>
                    <th>DAÑO</th>  
                    <th>DESCRIPCION</th>
                    <th style="width:80px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach($AfectacionDanoTerritorio as $danos):
                ?>
                <tr>
                    <td><?php echo $danos->territorio; ?></td>
                    <td><?php echo $danos->getDano()->getTipoDano()->nombre; ?></td>
                    <td><?php echo $danos->dano; ?></td>
                    <td><?php echo $danos->descripcion; ?></td>
                    <td class="btn-actions">  
                        <button id="btn-editar-dano-<?php echo $danos->id?>" type="button" class="btn btn-warning btn-icon-only fa fa-edit" data-loading-text="Cargando..." onclick="cargarModalEditarAfectacionDanoTerritorio(<?php echo $danos->id; ?>)"></button>                                              
                        <!--<button id="btn-editar-dano-<?php echo $danos->id?>" type="button" class="btn btn-warning btn-icon-only fa fa-edit" onclick="setVariablesEditar(<?php echo $danos->id.",".$dano->id.",'".$dano->nombre."'"; ?>)" data-toggle="modal" data-target="#modal_editar_dano"></button>-->
                        <button id="btn-eliminar-dano-<?php echo $dano->id?>" type="button" class="btn btn-danger btn-icon-only fa fa-minus" onclick="setVariablesEliminar(<?php echo $danos->id; ?>)" data-toggle="modal" data-target="#modal_eliminar_dano" title="Eliminar"></button>
                    </td>
                </tr>
                <?php
                endforeach;                
                ?>
            </tbody>
        </table>
            </div>
    </div>
     
      </div>
         </div>   
</div> 
<div id="div_modal_editar"></div>
<div class="modal fade" id="modal_eliminar_dano">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Eliminar daño</h4>
                  </div>
                  <div class="modal-body">
                    ¿Está seguro que desea eliminar este daño?                 
                  </div>
                  <div class="modal-footer">
                    <button id="btn-cancelar-eliminar-dano" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-eliminar-dano" type="button" class="btn btn-primary" onclick="eliminarAfectacionDanoTerritorio()" data-loading-text="Eliminando...">Eliminar</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->



<!--      //////////////////////////////////  TERCERA PESTAÑA-->
        <div class="tab-pane <?php echo $tab_3_active; ?>" id="tab3">
             <div class="row">
                 <div class="col-md-12">
                     <?php View::partial('fuentes/editar', false, array('fuentes'=>$fuentes)); ?>  
                 </div>
             </div>
               <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Actualizar Cultivo Ilícito'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>
    </div> 
    </div>
     <?php echo DwForm::close(); ?> 
</div>




    
    <script type='text/javascript'>
    let afectacion_dano_territorio_id = '';
    $("#btn-agregar-dano").prop('disabled', true);

    $(".formato_punto_coma").priceFormat(
    {
        prefix: '',
        centsLimit: 2,
        centsSeparator: ',',
        thousandsSeparator: '.'
    }); 
    
    $(".formato_punto").priceFormat(
    {
        prefix: '',
        centsLimit: 0,
        centsSeparator: ',',
        thousandsSeparator: '.'
    }); 
        
 $("#caso_departamento_id").on('change', function(e) {
            var departamento_id = $('#caso_departamento_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_municipios/'; ?>"+departamento_id+"/caso.municipio_id/Municipio/no/",
                data: "departamento_id=" + departamento_id + "&field=caso.municipio_id&label=Municipio&input_required=no",
            }).done(function(data) {
                
                $("#div_municipio").html(data);
                $("#caso_municipio_id").focus();
                $('#caso_territorio_id').val('');
            }).fail(function() {
                alert("error");
            });
        });
        
        $("#caso_municipio_id").on('change', function(e) {
            var municipio_id = $('#caso_municipio_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_territorios_municipio/'; ?>"+municipio_id+"/caso.territorio_id/Territorio/",
                data: "departamento_id=" + municipio_id + "&field=caso.territorio_id&label=Territorio",
            }).done(function(data) {
                $("#div_territorio").html(data);
                $("#caso_territorio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
                  
       if($('#cultivo_ilicito_part_comunidad').val() == 'SI')
        { $('#div_tipo_part_comunidad').show();
        }else{$('#div_tipo_part_comunidad').hide();}
              
        $("#cultivo_ilicito_part_comunidad").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_part_comunidad').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_tipo_part_comunidad').show();                   
                        //$('#cultivo_ilicito_otra_actividad_cual').focus(); 
                    }
                    else
                    {
                       $('#div_tipo_part_comunidad').hide();
                       //$('#cultivo_ilicito_otra_actividad_cual').val('');
                    }

        });
        
        if($('#cultivo_ilicito_part_otro').val() == 'SI')
        { $('#div_tipo_part_otro').show();
            $('#div_part_otro_quien').show();
        }else{$('#div_tipo_part_otro').hide();
        $('#div_part_otro_quien').hide();}
              
        $("#cultivo_ilicito_part_otro").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_part_otro').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_tipo_part_otro').show(); 
                        $('#div_part_otro_quien').show();
                        //$('#cultivo_ilicito_otra_actividad_cual').focus(); 
                    }
                    else
                    {
                       $('#div_tipo_part_otro').hide();
                       $('#div_part_otro_quien').hide();
                       //$('#cultivo_ilicito_otra_actividad_cual').val('');
                    }

        });
        
        
        
        if($('#cultivo_ilicito_contratada').val() == 'SI')
        { $('#div_contratada_quienes').show();
            
        }else{$('#div_contratada_quienes').hide();
        }
              
        $("#cultivo_ilicito_contratada").change(
        function(){
                var si_no 	=	$('#cultivo_ilicito_contratada').val();
                if( si_no == 'SI')
                    {                        
                        $('#div_contratada_quienes').show();                         
                        $('#cultivo_ilicito_contratada_quienes').focus(); 
                    }
                    else
                    {
                       $('#div_contratada_quienes').hide();                       
                    }

        });

        function deshabilitar_modal_dano() {
            $("#btn-agregar-dano").prop('disabled', true); 
            $('#afectacion_dano_territorio_descripcion').val('');
            $('#afectacion_dano_territorio_territorio_id').val('');
            $('#afectacion_dano_territorio_dano_id').val('');
            $('#afectacion_dano_territorio_tipo_dano_id').val('');
        }
        
        function validarBotonAgregarDano(){
            var territorio_id = $('#afectacion_dano_territorio_territorio_id').val();
            var tipo_dano_id = $('#afectacion_dano_territorio_tipo_dano_id').val();
            var dano_id = $('#caso_dano_territorio_dano_id').val();
            var descripcion = $('#afectacion_dano_territorio_descripcion').val();
            
            if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                $("#btn-agregar-dano").prop('disabled', false);
            }else{
                $("#btn-agregar-dano").prop('disabled', true);
            }
        }
        
        function agregarDano() {
        $("#btn-cancelar-agregar-dano").prop('disabled', true);
        let btn = $('#btn-agregar-dano');
        btn.button('loading');
        let modal = $("#modal-agregar-dano");
        let afectacion_id = $('#cultivo_ilicito_afectacion_id').val();
        let dano_id = $('#caso_dano_territorio_dano_id').val();
        let territorio_id = $('#afectacion_dano_territorio_territorio_id').val();
        let descripcion = $('#afectacion_dano_territorio_descripcion').val();
        
        let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/agregar_dano_afectacion/'; ?>";    

        let datos = {
                    "afectacion_id" : afectacion_id,
                    "dano_id" : dano_id,
                    "territorio_id" : territorio_id,
                    "descripcion" : descripcion
                    };

        $.ajax(url, {
            data: datos,
            method: 'POST',
            success: function (data, textStatus, jqXHR) {  
                $("#div_gestion_danos").html(data);
                btn.button('reset');
                modal.modal('hide');
                $("#btn-cancelar-agregar-dano").prop('disabled', false); 
                
                $('#afectacion_dano_territorio_descripcion').val('');
                $('#afectacion_dano_territorio_territorio_id').val('');
                $('#afectacion_dano_territorio_dano_id').val('');
                $('#afectacion_dano_territorio_tipo_dano_id').val('');                  
                $("#alert-id-guardar-dano").show();
                $("#alert-id-guardar-dano").hide().fadeIn(500).delay(4000).fadeOut(500);                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('ERROR en agregarDano()');
                btn.button('reset');
            }
        });
    }
        
        function setVariablesEliminar(afectacion_dano_territorio_id_) {
            afectacion_dano_territorio_id = afectacion_dano_territorio_id_;        
        }
        
        function eliminarAfectacionDanoTerritorio(){
            let afectacion_id = $('#cultivo_ilicito_afectacion_id').val();
            $("#btn-cancelar-eliminar-dano").hide();
            let btn = $('#btn-eliminar-dano');
            btn.button('loading');
            let modal = $("#modal_eliminar_dano");
            //let nombre_dano = $("#dano_nombre").val();
            let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/eliminar_dano_afectacion/'; ?>";    

            let datos = {
                        "afectacion_id" : afectacion_id,
                        "afectacion_dano_territorio_id" : afectacion_dano_territorio_id
                        };

            $.ajax(url, {
                data: datos,
                method: 'POST',
                success: function (data, textStatus, jqXHR) {  
                    $("#div_gestion_danos").html(data);
                    btn.button('reset');
                    modal.modal('hide');
                    $("#btn-cancelar-eliminar-dano").show();
                    $("#alert-id-eliminar").show();
                    $("#alert-id-eliminar").hide().fadeIn(500).delay(4000).fadeOut(500);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#btn-cancelar-eliminar-dano").show();
                    alert('ERROR en eliminarDano()');
                    btn.button('reset');
                }
            });
        }
         $("#afectacion_dano_territorio_tipo_dano_id").on('change', function(e) {
            var tipo_dano_id = $('#afectacion_dano_territorio_tipo_dano_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_danos/'; ?>"+tipo_dano_id+"/",
                data: "tipo_dano_id=" + tipo_dano_id,
            }).done(function(data) {
                $("#div_select_dano").html(data);
                $("#afectacion_dano_territorio_dano_id").focus();
            }).fail(function() {
                alert("error");
            });
        });

        function cargarModalEditarAfectacionDanoTerritorio(afectacion_dano_territorio_id){
            jsSpinner('show');
            let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/cargar_editar_dano_afectacion/'; ?>";    

            let datos = {
                        "afectacion_dano_territorio_id" : afectacion_dano_territorio_id
                        };

            $.ajax(url, {
                data: datos,
                method: 'POST',
                success: function (data, textStatus, jqXHR) {  
                    jsSpinner('hide');
                    $("#div_modal_editar").html(data);
                    let modal = $("#modal-editar-dano");                    
                    modal.modal('show');
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    jsSpinner('hide');
                    alert('ERROR en cargarModalEditarAfectacionDanoTerritorio()');
                }
            });
        }

        function validarBotonEditarDano(){
            var territorio_id = $('#editar_afectacion_dano_territorio_territorio_id').val();
            var tipo_dano_id = $('#editar_afectacion_dano_territorio_tipo_dano_id').val();
            var dano_id = $('#editar_afectacion_dano_territorio_dano_id').val();
            var descripcion = $('#editar_afectacion_dano_territorio_descripcion').val();
            
            if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                $("#btn-guardar-cambio-dano").prop('disabled', false);
            }else{
                $("#btn-guardar-cambio-dano").prop('disabled', true);
            }            
        }

        function onChangeTipoDanoEditar(){
                  
                  var tipo_dano_id = $('#editar_afectacion_dano_territorio_tipo_dano_id').val();
                  var datos = {
                      "tipo_dano_id" : tipo_dano_id
                  };
                  var url = "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_danos_editar/'; ?>";
                  
                  $.ajax(url, {
                      data: datos,
                      method: 'POST',
                      success: function (data, textStatus, jqXHR) {  
                          $("#div_select_dano_editar").html(data);
                          //let modal = $("#modal-editar-dano");
                          $("#div_select_dano_editar").html(data);
                          $("#editar_afectacion_dano_territorio_dano_id").focus();  
                          
                          var territorio_id = $('#editar_afectacion_dano_territorio_territorio_id').val();
                          var tipo_dano_id = $('#editar_afectacion_dano_territorio_tipo_dano_id').val();
                          var dano_id = $('#editar_afectacion_dano_territorio_dano_id').val();
                          var descripcion = $('#editar_afectacion_dano_territorio_descripcion').val();  
                          if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                              $("#btn-guardar-cambio-dano").prop('disabled', false);
                          }else{
                              $("#btn-guardar-cambio-dano").prop('disabled', true);
                          }
                      },
                      error: function (jqXHR, textStatus, errorThrown) {
                          alert('ERROR en cargarDano');
                      }
                  });
              }

    function guardarCambiosDano() {
        $("#btn-cancelar-guardar-cambio-dano").prop('disabled', true);
        let btn = $('#btn-guardar-cambio-dano');
        btn.button('loading');
        let modal = $("#modal-editar-dano");
        let afectacion_id = $('#cultivo_ilicito_afectacion_id').val();
        let afectacion_dano_territorio_id = $('#afectacion_dano_territorio_id').val();
        let dano_id = $('#editar_afectacion_dano_territorio_dano_id').val();
        let territorio_id = $('#editar_afectacion_dano_territorio_territorio_id').val();
        let descripcion = $('#editar_afectacion_dano_territorio_descripcion').val();
        
        let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/guardar_cambios_dano_afectacion/'; ?>";    

        let datos = {
                    "afectacion_id" : afectacion_id,
                    "afectacion_dano_territorio_id" : afectacion_dano_territorio_id,
                    "dano_id" : dano_id,
                    "territorio_id" : territorio_id,
                    "descripcion" : descripcion
                    };

        $.ajax(url, {
            data: datos,
            method: 'POST',
            success: function (data, textStatus, jqXHR) {  
                $("#div_gestion_danos").html(data);
                btn.button('reset');
                modal.modal('hide');
                $("#btn-cancelar-guardar-cambio-dano").prop('disabled', false); 
                
//                $('#afectacion_dano_territorio_descripcion').val('');
//                $('#afectacion_dano_territorio_territorio_id').val('');
//                $('#afectacion_dano_territorio_dano_id').val('');
//                $('#afectacion_dano_territorio_tipo_dano_id').val('');                  
                $("#alert-id-guardar-cambio-dano").show();
                $("#alert-id-guardar-cambio-dano").hide().fadeIn(500).delay(4000).fadeOut(500);                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('ERROR en guardarCambiosDano()');
                btn.button('reset');
            }
        });
    }
        
        
        
        
</script>