<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
     
    <ul class="nav nav-tabs nav-justified hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="disabled"><a href="#">Víctimas</a></li>       
        <li class="disabled"><a href="#">Actos victimizantes</a></li> 
        <li class="disabled"><a href="#">Daños</a></li>         
    </ul>
    <ul class="nav nav-tabs nav-justified visible-xs">    
        <li class="tab-pane active"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Víctimas</a></li>        
        <li class="tab-pane <?php echo $tab_3_active; ?>" ><a href="#tab3" data-toggle="tab">Actos victimizantes</a></li>
        <li class="tab-pane <?php echo $tab_4_active; ?>" ><a href="#tab4" data-toggle="tab">Daños</a></li>        
    </ul>
    
    
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <div class="row">
                <div id="div_advertencia" class="col-md-6">
                    <div class="row">
                        <div class="alert alert-warning">                    
                            <strong>¡Advertencia!</strong> Este tipo de caso debe tener 3 o más víctimas. 
                        </div>
                    </div>   
                </div>                
                <div class="col-md-12">
                <div class="row">    
                    <div class="col-md-3">                         
                        <?php echo DwForm::dbSelect('caso.tipo_caso_id', 'nombre', array('violencia_politica/tipo_caso', 'getListadoTipoCasoDBS', TipoCaso::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Tipo de caso'); ?>                                                
                    </div>
                    <div class="col-md-9">
                        <?php echo DwForm::text('caso.titulo', array('class'=>'input-required'), NULL, 'Título del caso'); ?>
                    </div>
                   </div>
                       <div class="row">
                        <div class="col-md-3" id="div_departamento"> 
                            <?php echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS', Departamento::ACTIVO), NULL, array('class'=>'input-required'), NULL, 'Departamento'); ?>
                            <?php //echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('commons/departamento', 'findByPais', (isset($usuario->pais_de_expedicion_id)) ? $usuario->pais_de_expedicion_id : '52'), NULL, array('class' => 'input-required'), (isset($usuario->departamento_de_expedicion_id)) ? $usuario->departamento_de_expedicion_id : NULL, 'Departamento de expedición'); ?>
                        </div>
                        <div class="col-md-3" id="div_municipio">                    
                            <?php echo DwForm::dbSelect('caso.municipio_id', 'nombre', array('observatorio/municipio', 'getMunicipioPorDepartamento',  NULL), NULL, array('class' => 'input-required'), NULL, 'Municipio'); ?>
                        </div>
                       <div class="col-md-6" id="div_territorio">                    
                            <?php //echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', (isset($caso->municipio_id)) ? $caso->municipio_id : NULL), NULL, array('class' => 'input-required'), (isset($usuario->territorio_id)) ? $caso->territorio_id : NULL, 'Territorio'); ?>
                           <?php echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', NULL), NULL, array('class' => ''), NULL, 'Territorio'); ?>
                        </div>  
                           </div>
                       <div class="row">
                        <div class="col-md-3">
                            <?php echo DwForm::number('caso.cantidad_victima', array('class'=>'input-integer', 'placeholder'=>'INDETERMINADO'), NULL, 'Cantidad de víctimas'); ?>
                        </div>   
                        <div class="col-md-3">
                            <?php echo DwForm::date('caso.fecha_desde', array('class'=>'input-required'), '', 'Fecha en que ocurrió el caso | DD-MM-YYYY'); ?>
                        </div> 
                       <div class="col-md-3">
                            <?php /*echo DwForm::date('caso.fecha_hasta', array('class'=>'input-required'), '', 'Fecha en que finalizó el caso'); */?>
                        </div> 
                    </div>                    
                    <div class="row">
                        <div class="col-md-9">
                            <?php echo DwForm::textarea('caso.descripcion', array('class'=>'input-lower', 'required'=>'required', 'style'=>"height: 200px;"), '', 'Descripción del caso'); ?>
                        </div>                
                    </div> 
                    
                    <div class="row">
                         <div class="col-md-12">               
               <label for="panel_fuente"><h3 class="panel-title">Fuente(s) de la información</h3></label>               
                 <div id="panel_fuente" class="panel panel-default">
                     <div class="panel-body">
                        <?php View::partial('fuentes/agregar', false, NULL); ?>
                    </div>                    
                </div>
            </div> 
                    </div>
            </div>
                </div>
             <div class="row">
            <div class="form-actions">
                <?php echo DwForm::sendContinue('Continuar'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('caso.titulo'); ?>
            </div>
        </div>
        </div>
                        
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
 <div class="tab-pane <?php echo $tab_2_active; ?>" id="tab2">
           
    </div> 
<!--      //////////////////////////////////  TERCERA PESTAÑA-->

 <div class="tab-pane <?php echo $tab_3_active; ?>" id="tab3">
            
    </div> 


<!--      //////////////////////////////////  CUARTA PESTAÑA-->

 <div class="tab-pane <?php echo $tab_4_active; ?>" id="tab4">        
             
    </div> 



    </div>
     <?php echo DwForm::close(); ?> 
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#div_advertencia").hide();

 $("#caso_departamento_id").on('change', function(e) {
            var departamento_id = $('#caso_departamento_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_municipios/'; ?>"+departamento_id+"/caso.municipio_id/Municipio/no/",
                data: "departamento_id=" + departamento_id + "&field=caso.municipio_id&label=Municipio&input_required=no",
            }).done(function(data) {
                $("#div_municipio").html(data);
                $("#caso_municipio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
        $("#caso_municipio_id").on('change', function(e) {
            var municipio_id = $('#caso_municipio_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_territorios_municipio/'; ?>"+municipio_id+"/caso.territorio_id/Territorio/",
                data: "departamento_id=" + municipio_id + "&field=caso.territorio_id&label=Territorio",
            }).done(function(data) {
                $("#div_territorio").html(data);
                $("#caso_territorio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
        $("#caso_tipo_caso_id").on('change', function(e) {
            var tipo_caso_id = $('#caso_tipo_caso_id').val();
            if(tipo_caso_id === '2'){
                $("#div_advertencia").show();
                //$("#caso_cantidad_victima").val('3');
            }else{
                $("#div_advertencia").hide();
                //$("#caso_cantidad_victima").val('1');
            }
            
        });
        
         });
         
        
</script>