<?php View::flash(); ?>
<div id="div_modal_editar_victima">
 <div class="modal fade" id="modal-editar-victima">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Editar Víctima</h4>
                </div>
      
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
               <div class="row">  
                   <?php echo DwForm::hidden("victima.editar_caso_id", NULL, $Victima->caso_id);?> 
                   <?php echo DwForm::hidden("victima.editar_id", NULL, $victima_id);?>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="victima_editar_nombre">Nombre(s) y Apellido(s)<span class="req">*</span></label>
                                <?php echo DwForm::text('victima.editar_nombre', array('onkeyup'=>'validarBotonGuardarCambioVictima()'), $Victima->nombre, 'Nombre(s) y Apellido(s)'); ?>
                            </div>    
                        </div>                        
                        <div class="col-md-3">
                            <label for="victima_editar_genero_id">Género<span class="req">*</span></label>
                        <?php echo DwForm::dbSelect('victima.editar_genero_id', 'nombre', array('opcion/genero', 'getListadoGeneroDBS', Genero::ACTIVO), NULL, array('onchange'=>'validarBotonGuardarCambioVictima()'), $Victima->genero_id, 'Género'); ?>
                        </div>
                    <div class="col-md-3">
                        <label for="victima_editar_edad">Edad</label>
                        <?php echo DwForm::number('victima.editar_edad', array('class'=>'input-integer', 'placeholder'=>'SIN INFORMACIÓN'), $Victima->edad, 'Edad'); ?>
                    </div>
               </div>
                 <div class="row">                   
                     <div class="col-md-6">
                         <div class="form-group">
                            <label for="victima_editar_ocupacion">Ocupación<span class="req">*</span></label>
                            <?php echo DwForm::text('victima.editar_ocupacion', array('onkeyup'=>'validarBotonGuardarCambioVictima()'), $Victima->ocupacion, 'Ocupación'); ?>
                        </div>
                    </div>                        
                    <div class="col-md-6">
                        <label for="victima_editar_caracterizacion_id">Perfil<span class="req">*</span></label> 
                        <?php echo DwForm::dbSelect('victima.editar_caracterizacion_id', 'nombre', array('opcion/caracterizacion', 'getListadoCaracterizacionDBS', Caracterizacion::ACTIVO), NULL, array('onchange'=>'validarBotonGuardarCambioVictima()'), $Victima->caracterizacion_id, 'Perfil'); ?>
                    </div>
                        
               </div>
                <div class="row">               
                    <div class="col-md-6">
                        <div class="form-group">
                        <label for="victima_editar_etnia_id">Etnia</label>
                        <?php echo DwForm::dbSelect('victima.editar_etnia_id', 'nombre', array('opcion/etnia', 'getListadoEtniaDBS', 'etnia'), NULL, array('class'=>'', 'onchange'=>'onChangeEditarEtniaId()'), $Victima->etnia_id, 'Etnia'); ?>
                        </div>
                    </div>
                    
                    <div id="div_editar_etnia_indigena_id" class="col-md-6" <?php if($Victima->etnia_id !='2'){echo 'hidden';}?>>
                        <label for="victima_editar_etnia_indigena_id">Etnia indígena</label>
                        <?php echo DwForm::dbSelect('victima.editar_etnia_indigena_id', 'nombre', array('opcion/etnia', 'getListadoEtniaDBS', 'indigena'), NULL, array('class'=>''), $Victima->etnia_indigena_id, 'Etnia indígena'); ?>
                    </div>
                </div>
                <div class="row">
                     <div class="col-md-12">
                 <label for="panel_antecedentes">Antecedentes de la víctima relacionados con violencia</label>
                    <div id="panel_antecedentes" class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-md-12">
                                <?php echo DwForm::dbCheckId('editar_antecedente_violencia','nombre',array('opcion/antecedente_violencia','getListadoAntecedenteViolenciaDBS'), array('onchange'=>'', 'class'=>'editar_antecedente_violencia'), $antecedente_violencia, 3, '4'); ?>
                            </div>
                        </div>
                    </div> 
             </div>  
                </div>
               
            </div>             
        </div> 
                </div>
                <div class="modal-footer">
                    <button id="btn-cancelar-guardar-cambio-victima" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-guardar-cambio-victima" type="button" class="btn btn-success" onclick="guardarCambiosVictima()" data-loading-text="Guardando...">Guardar cambios</button>
                </div>
                
                
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>