<?php View::flash(); ?>

<div class="container shell-view">

    <?php $caso->nombre = $caso->titulo;
    View::process_estado_nivel('caso', $caso, $page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
     
    <ul class="nav nav-tabs nav-justified hidden-xs">
        <li class="<?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="<?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Víctimas</a></li>       
        <li class="<?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Hechos victimizantes</a></li>
        <li class="<?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Daños</a></li>
        <li class="<?php echo $tab_5_active; ?>"><a href="#tab5" data-toggle="tab">Fuente(s) de la información</a></li>         
    </ul>
    <ul class="nav nav-tabs nav-justified visible-xs">    
        <li class="tab-pane <?php echo $tab_1_active; ?>"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li class="tab-pane <?php echo $tab_2_active; ?>"><a href="#tab2" data-toggle="tab">Víctimas</a></li>        
        <li class="tab-pane <?php echo $tab_3_active; ?>"><a href="#tab3" data-toggle="tab">Hechos victimizantes</a></li>
        <li class="tab-pane <?php echo $tab_4_active; ?>"><a href="#tab4" data-toggle="tab">Daños</a></li>
        <li class="tab-pane <?php echo $tab_5_active; ?>"><a href="#tab5" data-toggle="tab">Fuente(s) de la información</a></li>         
    </ul>
    
    <div class="tab-content">
        <div class="tab-pane <?php echo $tab_1_active; ?>" id="tab1">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">                  
                    <div class="col-md-3">
                        <?php
                        echo DwForm::text('numero', array('class'=>'input-disabled'), $caso->id.substr($caso->getMunicipio()->getDepartamento()->nombre,0, 2) , 'Número del caso'); ?>
                    </div>
                    <div class="col-md-3">
                        <?php
                        echo DwForm::text('fecha_registro', array('class'=>'input-disabled'), $caso->caso_at , 'Fecha de registro'); ?>
                    </div>
                    <div class="col-md-3">
                        <?php
                        echo DwForm::text('ultima_actualizacion', array('class'=>'input-disabled'), $caso->caso_in , 'Fecha última actualización'); ?>
                    </div>
                </div>
                <div class="row">                 
                    <div class="col-md-3"> 
                        <?php echo DwForm::dbSelect('caso.tipo_caso_id', 'nombre', array('violencia_politica/tipo_caso', 'getListadoTipoCasoDBS', TipoCaso::ACTIVO), NULL, array('class'=>'input-required'), $caso->tipo_caso_id, 'Tipo de caso'); ?>                        
                    </div>
                    <div class="col-md-9">
                        <?php echo DwForm::hidden("caso.id", NULL, NULL);?> 
                        <?php echo DwForm::text('caso.titulo', array('class'=>'input-required'), NULL, 'Título del caso'); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" id="div_departamento"> 
                         <?php echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('observatorio/departamento', 'getListadoDepartamentoDBS', Departamento::ACTIVO), NULL, array('class'=>'input-required'), $departamento_id, 'Departamento'); ?>
                         <?php //echo DwForm::dbSelect('caso.departamento_id', 'nombre', array('commons/departamento', 'findByPais', (isset($usuario->pais_de_expedicion_id)) ? $usuario->pais_de_expedicion_id : '52'), NULL, array('class' => 'input-required'), (isset($usuario->departamento_de_expedicion_id)) ? $usuario->departamento_de_expedicion_id : NULL, 'Departamento de expedición'); ?>
                    </div>
                    <div class="col-md-3" id="div_municipio">                    
                         <?php echo DwForm::dbSelect('caso.municipio_id', 'nombre', array('observatorio/municipio', 'getMunicipioPorDepartamento',  $departamento_id), NULL, array('class' => 'input-required'), NULL, 'Municipio'); ?>
                    </div>
                    <div class="col-md-6" id="div_territorio">                    
                         <?php //echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', (isset($caso->municipio_id)) ? $caso->municipio_id : NULL), NULL, array('class' => 'input-required'), (isset($usuario->territorio_id)) ? $caso->territorio_id : NULL, 'Territorio'); ?>
                        <?php echo DwForm::dbSelect('caso.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', $caso->municipio_id), NULL, array('class' => ''), NULL, 'Territorio'); ?>
                    </div>  
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <?php echo DwForm::number('caso.cantidad_victima', array('class'=>'input-required'), NULL, 'Cantidad de victimas'); ?>
                    </div>   
                    <div class="col-md-3">
                        <?php echo DwForm::date('caso.fecha_desde', array('class'=>'input-required'), NULL, 'Fecha en que ocurrió el caso | AAAA-MM-DD'); ?>
                    </div> 
                    <div class="col-md-3">
                        <?php /*echo DwForm::date('caso.fecha_hasta', array('class'=>'input-required'), NULL, 'Fecha en que finalizó el caso');*/ ?>
                    </div> 
                </div>                    
                    <div class="row">
                        <div class="col-md-9">
                            <?php echo DwForm::textarea('caso.descripcion', array('class'=>'input-lower', 'required'=>'required', 'style'=>"height: 200px;"), NULL, 'Descripción del caso'); ?>
                        </div>                
                    </div>                 
            </div>
            </div>
             <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Actualizar caso'); ?>
                <?php 
                if(Session::get('query_busqueda_caso') != '')
                {
                    echo DwForm::cancel('violencia_politica/casos/consulta/si/'); 
                }
                else {
                    echo DwForm::cancel(); 
                }
                ?>
            </div>
        </div>
        </div>

<?php echo DwForm::close();  ?>        
        
                
<!--      //////////////////////////////////  SEGUNDA PESTAÑA-->
 <div class="tab-pane <?php echo $tab_2_active; ?>" id="tab2">  
     <div class="row">
    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <div class="col-md-3">
                <?php echo DwHtml::button("violencia_politica/casos/agregar_victima/$caso->id/", 'agregar victima', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX); ?>
                </div>             
            </div>            
        </div>
    </div>
                 
                     <div class="container-overflow">
                         
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th>NOMBRE</th>                    
                    <th>EDAD</th>
                    <th>GENERO</th>   
                    <th>PERFIL</th>   
                    <th class="btn-actions col-blocked text-center">ESTADO</th>
                    <th class="btn-actions col-blocked text-center">OPCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $contador_victima = 1;
                foreach($victimas as $victima): ?>
                    
                    <?php //$key_show = Security::setKey($victima->id, 'show_victima'); ?>
                    <?php $key_upd = Security::setKey($victima->id, 'upd_victima'); ?>                    
                    <?php $key_del = Security::setKey($victima->id, 'del_victima'); ?>                    
                    <tr>
                        <td><?php echo $contador_victima; ?></td>
                        <td><?php echo $victima->nombre.' '.$victima->apellido; ?></td>
                        <td><?php echo ($victima->edad === '') ? 'Sin información' : $victima->edad; ?></td>
                        <td><?php try { echo $victima->getGenero()->nombre; } catch (Exception $exc) {} ?></td>
                        <td><?php try { echo $victima->getCaracterizacion()->nombre; } catch (Exception $exc) {} ?></td>
                        <td class="btn-actions"><?php View::partial('nivel_estado/ver', false, array('nivel'=>$victima->nivel, 'estado'=>$victima->estado)); ?>
                        <td class="btn-actions">
                            <?php View::partial('opcion/ver', false, 
                                    array('elemento'=>'víctima',
                                        "nombre"=>$victima->nombre,
                                        'url_ver'=>NULL,
                                        'url_editar'=>"violencia_politica/casos/editar_victima/$key_upd/",
                                        "url_eliminar"=>"violencia_politica/casos/eliminar_victima/$victima->nombre/$caso->titulo/$key_del/$caso->id/")); ?>                      
                        </td>                                        
                    </tr>
                    <?php $contador_victima++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
             </div>
     
<!--    <div class="row">
        <div class="row">
            <div class="form-actions">
                 <?php echo DwForm::cancel($url_redir_back); ?>
            </div>
        </div>
    </div>-->
</div> 

<!--      //////////////////////////////////  TERCERA PESTAÑA-->

 <div class="tab-pane <?php echo $tab_3_active; ?>" id="tab3">
     <div class="row">
                <div class="col-md-12">
                    
                    
<div class="row"> 
    <div class="modal fade" id="modal-agregar-victimizacion">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar victimización al caso: <?php echo $caso->titulo; ?></h4>
                </div>
                <div class="modal-body">
                    <div class="row">  
                                    <div class="col-md-5">
                                        <?php echo DwForm::dbSelect('vhpr.victima_id', 'nombre', $victimas, NULL, array('class'=>'', 'onchange'=>'validarBotonAgregarVictimizacion()'), NULL, 'Víctima'); ?>    
                                    </div>
                                    <div class="col-md-3">
                                        <?php echo DwForm::dbSelect('vhpr.presunto_responsable_id', 'nombre', array('opcion/presunto_responsable', 'getListadoPresuntoResponsableDBS', PresuntoResponsable::ACTIVO), NULL, array('class'=>'', 'onchange'=>'validarBotonAgregarVictimizacion()'), NULL, 'Presunto responsable'); ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php echo DwForm::text('vhpr.descripcion_presunto_responsable', array('class'=>''), NULL, 'Descripción presunto responsable'); ?>
                                    </div>
                                </div>
                    <label for="panel-hechos-victimizantes">Hechos victimizantes</label>
                <div id="panel-hechos-victimizantes" class="panel panel-default">
                    <div class="panel-body">                                          
                        <div class="row">                      
                            <div class="col-md-12">                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo DwForm::dbCheckId('hecho_victimizante','nombre',array('opcion/hechovictimizante','getListadoHechovictimizanteDBS'), array('onclick'=>'validarBotonAgregarVictimizacion()', 'class'=>'hecho_victimizante'), NULL, 4, '3'); ?>
                                    </div>
                                </div>
                            </div>
                        </div>                                    
                    </div>
                </div>                    
                </div>
                <div class="modal-footer">
                    <button id="btn-cancelar-agregar-victimizacion" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-agregar-victimizacion" type="button" class="btn btn-primary" onclick="agregarVictimizacion()" data-loading-text="Agregando...">Agregar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <label for="panel_victimizacion"></label>
<!--    <div id="panel_victimizacion" class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12">
                <div class="row">                                    
                    <div class="col-md-3"> 
                          <?php echo DwForm::dbSelect('vhpr.presunto_responsable_id', 'nombre', array('opcion/presunto_responsable', 'getListadoPresuntoResponsableDBS', PresuntoResponsable::ACTIVO), NULL, array('class'=>'', 'class'=>'input-required'), NULL, 'Presunto responsable'); ?>
                        <?php echo DwForm::text('vhpr.descripcion_presunto_responsable', array('class'=>''), NULL, 'Descripción presunto responsable'); ?>
                    </div>                   
                    <div class="col-md-4"> 
                          <?php echo DwForm::dbSelect('vhpr.hechovictimizante_id', 'nombre', array('opcion/hechovictimizante', 'getListadoHechovictimizanteDBS', Hechovictimizante::ACTIVO), NULL, array('class'=>'', 'class'=>'input-required'), NULL, 'Hecho victimizante'); ?>
                    </div>           
                    <div class="col-md-4"> 
                        <?php echo DwForm::dbSelect('vhpr.victima_id', 'nombre', $victimas, NULL, array('class'=>'', 'class'=>'input-required'), NULL, 'Víctima'); ?>
                    </div> 
                    <div class="col-md-1">
                        <label for="boton_anadir"></label>
                        <a id="boton_anadir" href="#" class="btn btn-success disabled form-control" role="button">AÑADIR</a>
                    </div>                                    
                </div>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-3">
                    <?php //echo DwForm::text('vhpr.presunto_responsable_descripcion', array('class'=>''), NULL, 'Descripcion presunto responsable'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>           -->
</div> 
     
     
     
    <div class="container-overflow">
        <button style="margin-bottom: 5px;" id="btn-agregar" type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-agregar-victimizacion" onclick="deshabilitar()" >Agregar hechos victimizantes</button>
        <div id="div_gestion_vhpr">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>VICTIMA</th>
                    <th>HECHO VICTIMIZANTE</th>
                    <th>PRESUNTO RESPONSABLE</th>  
                    <th>DESCRIPCION PRESUNTO RESPONSABLE</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php
                 $Vhpr = new VictimaHechovictimizantePresuntoResponsable();
                $contador_victima = 1;
                foreach($victimas as $victima):  
                    $nombre_victima = '';
                    $nombre_presunto_resp = '';
                    $contador_hechos = 1;
                    foreach($Vhpr->getVictimaHechovictimizantePresuntoResponsableByVictimaId($victima->id) as $vhpr):   
                        $cap_nombre_victima = $vhpr->nombre_victima;
                        $cap_nombre_presunto_resp = $vhpr->nombre_presunto_responsable;                        
                        ?>
                <tr  <?php if ($contador_hechos === 1){echo 'style="border-top: red 2px solid;"';} ?>>                                                                       
                        <td><?php if ($contador_hechos === 1){echo $cap_nombre_victima;} ?></td>                        
                        <td><?php echo $vhpr->nombre_hechovictimizante; ?></td>
                        <td><?php if ($cap_nombre_presunto_resp != $nombre_presunto_resp){ echo $cap_nombre_presunto_resp;} 
                                  else {} ?></td>
                        <td><?php if ($cap_nombre_presunto_resp != $nombre_presunto_resp){ echo $vhpr->descripcion_presunto_responsable;} 
                                  else {} ?></td>
                        <td>
                            <?php //echo DwHtml::buttonTable('Ver victima', "observatorio/territorios/ver_victima/$key_show/$obj_territorio->tipo/$key/", null, 'info', 'fa-search'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar', "violencia_politica/casos/eliminar_vhpr/$caso->id/$vhpr->id/",
                                            array('class'=>'js-confirm', 'msg-title'=>'Eliminar:', 'msg'=>'¿Está seguro de eliminar esta victimización? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-minus');
                                 ?>                            
                        </td>
                    </tr>
                        <?php
                        $nombre_presunto_resp = $cap_nombre_presunto_resp;
                        $contador_hechos++;
                    endforeach;           
                    ?>               
                    <?php $contador_victima++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
            </div>
    </div>
     
      </div>
         </div>
          
      </div>
 

<!-- //////////////////////////////////  CUARTA PESTAÑA -->

 <div class="tab-pane <?php echo $tab_4_active; ?>" id="tab4">
    <div class="row">
        <div class="col-md-12">
                    
                    
<div class="row"> 
    <div class="modal fade" id="modal-agregar-dano">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Agregar daño al caso: <?php echo $caso->titulo; ?></h4>
                </div>
                <div class="modal-body">
                    <div class="row">  
                        <div class="col-md-12">
                            <?php echo DwForm::dbSelect('caso_dano_territorio.territorio_id', 'nombre', array('observatorio/territorio_municipio', 'getTerritoriosByMunicipioIdSelect', $caso->municipio_id), NULL, array('class' => '', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Territorio afectado'); ?>
                            <?php echo DwForm::dbSelect('caso_dano_territorio.tipo_dano_id', 'nombre', array('opcion/tipo_dano', 'getListadoTipoDanoDBS', NULL), NULL, array('class' => '', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Tipo de daño'); ?>
                            <div id="div_select_dano">
                                <?php echo DwForm::dbSelect('caso_dano_territorio.dano_id', 'nombre', array('opcion/dano', 'getDanoByTipoDanoIdDBS', NULL), NULL, array('class'=>'', 'onchange'=>'validarBotonAgregarDano()'), NULL, 'Daño'); ?>
                            </div>
                            <?php echo DwForm::textarea('caso_dano_territorio.descripcion', array('class'=>'input-lower', 'onkeyup'=>'validarBotonAgregarDano()', 'style'=>"height: 130px;"), NULL, 'Descripción del daño'); ?>
                        </div>                       
                    </div>                                   
                </div>
                <div class="modal-footer">
                    <button id="btn-cancelar-agregar-dano" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-agregar-dano" type="button" class="btn btn-primary" onclick="agregarDano()" data-loading-text="Agregando...">Agregar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <label for="panel_danos"></label>
</div>  
    <div class="container-overflow">
        <button style="margin-bottom: 5px;" id="btn-agregar" type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-agregar-dano" onclick="deshabilitar_modal_dano()" >Agregar daño</button>
        <div id="div_gestion_danos">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>TERRITORIO</th>
                    <th>TIPO DE DAÑO</th>
                    <th>DAÑO</th>  
                    <th>DESCRIPCION</th>
                    <th style="width:80px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach($CasoDanoTerritorio as $danos):
                ?>
                <tr>
                    <td><?php echo $danos->territorio; ?></td>
                    <td><?php echo $danos->getDano()->getTipoDano()->nombre; ?></td>
                    <td><?php echo $danos->dano; ?></td>
                    <td><?php echo $danos->descripcion; ?></td>
                    <td class="btn-actions">                                                
                        <button id="btn-editar-dano-<?php echo $danos->id?>" type="button" class="btn btn-warning btn-icon-only fa fa-edit" onclick="cargarModalEditarCasoDanoTerritorio(<?php echo $danos->id; ?>)"></button>
                        <button id="btn-eliminar-dano-<?php echo $dano->id?>" type="button" class="btn btn-danger btn-icon-only fa fa-minus" onclick="setVariablesEliminar(<?php echo $danos->id; ?>)" data-toggle="modal" data-target="#modal_eliminar_dano" title="Eliminar"></button>
                    </td>
                </tr>
                <?php
                endforeach;                
                ?>
            </tbody>
        </table>
            </div>
    </div>
     
      </div>
         </div>
          
 </div>
      <div id="div_modal_editar"></div>
<div class="modal fade" id="modal_eliminar_dano">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Eliminar daño</h4>
                  </div>
                  <div class="modal-body">
                    ¿Está seguro que desea eliminar este daño?                 
                  </div>
                  <div class="modal-footer">
                    <button id="btn-cancelar-eliminar-dano" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="btn-eliminar-dano" type="button" class="btn btn-primary" onclick="eliminarCasoDanoTerritorio()" data-loading-text="Eliminando...">Eliminar</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->


<!--      //////////////////////////////////  QUINTA PESTAÑA-->

 <div class="tab-pane <?php echo $tab_5_active; ?>" id="tab5">
             <div class="row">
                 <div class="col-md-12">
<!--                     <div class="row">                                
                          <div  class="col-md-2">                                    
                            <?php echo DwForm::date('fuente.fecha', array('class'=>''), NULL, 'Fecha de la fuente'); ?>                                    
                          </div>
                          <div class="col-md-8">                                   
                            <?php echo DwForm::text('fuente.nombre', array('class'=>'input-lower'), NULL, 'Descripcion de la fuente'); ?>                                  
                          </div>   
                         <div class="col-md-2">
              <label for="boton_anadir_fuente"></label>
              <a id="boton_anadir_fuente" href="#" class="btn btn-success disabled form-control" role="button">AÑADIR</a>
          </div>
                        </div>-->
                     <?php View::partial('fuentes/editar', false, array('fuentes'=>$fuentes)); ?>
                 </div>
             </div>
<!--               <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Actualizar caso'); ?>
                <?php echo DwForm::cancel($url_redir_back); ?>
            </div>
        </div>-->
    </div> 
    </div>
</div>
<div id="flash-message" class="flash-message">
    <div id="alert-id-guardar" class="alert alert-block alert-success" style="display: none;">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Los hechos victimizantes han sido agregados con exito.
    </div>
</div>
<div id="flash-message" class="flash-message">
    <div id="alert-id-guardar-dano" class="alert alert-block alert-success" style="display: none;">
        <button type="button" class="close" data-dismiss="alert">×</button>
        El daño al territorio se ha agregado con exito.
    </div>
</div>
<div id="flash-message" class="flash-message">
    <div id="alert-id-guardar-cambio-dano" class="alert alert-block alert-success" style="display: none;">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Los cambios del daño al territorio se han guardado con exito.
    </div>
</div>
<script type="text/javascript">
    let caso_dano_territorio_id = '';
    var hechosSeleccionados = new Array();
    $("#btn-agregar-victimizacion").prop('disabled', true);
    $("#btn-agregar-dano").prop('disabled', true);
    
    function validarBotonAgregarVictimizacion(){
            var presunto_responsable_id = $('#vhpr_presunto_responsable_id').val();
            var victima_id = $('#vhpr_victima_id').val();
            var cantidad_hechos = 0;
            var hechosSeleccionados_ = new Array();
            $('input[type=checkbox]:checked').each(function() {
                cantidad_hechos = cantidad_hechos + 1;
                hechosSeleccionados_.push($(this).val());
            });
            hechosSeleccionados = hechosSeleccionados_;
            if(cantidad_hechos > 0 && presunto_responsable_id !== '' && victima_id !== ''){
                $("#btn-agregar-victimizacion").prop('disabled', false);
            }else{
                $("#btn-agregar-victimizacion").prop('disabled', true);
            }
        }
    function agregarVictimizacion() {
        $("#btn-cancelar-agregar-victimizacion").prop('disabled', true);
        let btn = $('#btn-agregar-victimizacion');
        btn.button('loading');
        let modal = $("#modal-agregar-victimizacion");
        let caso_id = $('#caso_id').val();
        let presunto_responsable_id = $('#vhpr_presunto_responsable_id').val();
        let victima_id = $('#vhpr_victima_id').val();
        let descripcion_presunto_responsable = $('#vhpr_descripcion_presunto_responsable').val();
        
        let url = "<?php echo PUBLIC_PATH . 'violencia_politica/casos/gestion_vhpr/'; ?>";    

        let datos = {
                    "accion" : "crear",
                    "caso_id" : caso_id,
                    "victima_id" : victima_id,
                    "presunto_responsable_id" : presunto_responsable_id,
                    "descripcion_presunto_responsable" : descripcion_presunto_responsable,
                    "hechos_victimizantes" : hechosSeleccionados
                    };

        $.ajax(url, {
            data: datos,
            method: 'POST',
            success: function (data, textStatus, jqXHR) {  
                $("#div_gestion_vhpr").html(data);
                btn.button('reset');
                modal.modal('hide');
                $("#btn-cancelar-agregar-victimizacion").prop('disabled', false); 
                
                $('#vhpr_victima_id').val('');
                $('#vhpr_presunto_responsable_id').val('');
                $('#vhpr_descripcion_presunto_responsable').val('');                  
                $("#alert-id-guardar").show();
                $("#alert-id-guardar").hide().fadeIn(500).delay(4000).fadeOut(500);                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('ERROR en entregarPedido()');
                btn.button('reset');
            }
        });
    }
    /*$(document).ready(function() {*/
    function deshabilitar() {
        $("#btn-agregar-victimizacion").prop('disabled', true); 
        $(".hecho_victimizante").prop("checked", false);
    } 
        
 $("#caso_departamento_id").on('change', function(e) {
            var departamento_id = $('#caso_departamento_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_municipios/'; ?>"+departamento_id+"/caso.municipio_id/Municipio/no/",
                data: "departamento_id=" + departamento_id + "&field=caso.municipio_id&label=Municipio&input_required=no",
            }).done(function(data) {
                $("#div_municipio").html(data);
                $("#caso_municipio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
        $("#caso_municipio_id").on('change', function(e) {
            var municipio_id = $('#caso_municipio_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_territorios_municipio/'; ?>"+municipio_id+"/caso.territorio_id/Territorio/",
                data: "departamento_id=" + municipio_id + "&field=caso.territorio_id&label=Territorio",
            }).done(function(data) {
                $("#div_territorio").html(data);
                $("#caso_territorio_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        

        $("#fuente_nombre").on('keyup', function(e) {
            var fecha = $('#fuente_fecha').val();
            var nombre = $('#fuente_nombre').val();
            var caso_id = $('#caso_id').val();
            if(fecha != '' && nombre != '')
            {
                $('#boton_anadir_fuente').attr('href', 
                '/violencia_politica/casos/agregar_fuente/'+caso_id+'/'+fecha+'/'+nombre+'/');
                $('#boton_anadir_fuente').attr('class', 'btn btn-success form-control');
            }
            else
            {
                $('#boton_anadir_fuente').attr('class', 'btn btn-success disabled form-control');
            }
            
        });
        
         $("#fuente_fecha").on('keyup', function(e) {
            var fecha = $('#fuente_fecha').val();
            var nombre = $('#fuente_nombre').val();
            var caso_id = $('#caso_id').val();
            if(fecha != '' && nombre != '')
            {
                $('#boton_anadir_fuente').attr('href', 
                '/violencia_politica/casos/agregar_fuente/'+caso_id+'/'+fecha+'/'+nombre+'/');
                $('#boton_anadir_fuente').attr('class', 'btn btn-success form-control');
            }
            else
            {
                $('#boton_anadir_fuente').attr('class', 'btn btn-success disabled form-control');
            }
            
        });
        
        $("#caso_dano_territorio_tipo_dano_id").on('change', function(e) {
            var tipo_dano_id = $('#caso_dano_territorio_tipo_dano_id').val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_danos/'; ?>"+tipo_dano_id+"/",
                data: "tipo_dano_id=" + tipo_dano_id,
            }).done(function(data) {
                $("#div_select_dano").html(data);
                $("#caso_dano_territorio_dano_id").focus();
            }).fail(function() {
                alert("error");
            });
        });
        
        function deshabilitar_modal_dano() {
            $("#btn-agregar-dano").prop('disabled', true); 
            $('#caso_dano_territorio_descripcion').val('');
            $('#caso_dano_territorio_territorio_id').val('');
            $('#caso_dano_territorio_dano_id').val('');
            $('#caso_dano_territorio_tipo_dano_id').val('');
        }
        
        function validarBotonAgregarDano(){
            var territorio_id = $('#caso_dano_territorio_territorio_id').val();
            var tipo_dano_id = $('#caso_dano_territorio_tipo_dano_id').val();
            var dano_id = $('#caso_dano_territorio_dano_id').val();
            var descripcion = $('#caso_dano_territorio_descripcion').val();
            
            if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                $("#btn-agregar-dano").prop('disabled', false);
            }else{
                $("#btn-agregar-dano").prop('disabled', true);
            }
        }
        
        function agregarDano() {
        $("#btn-cancelar-agregar-dano").prop('disabled', true);
        let btn = $('#btn-agregar-dano');
        btn.button('loading');
        let modal = $("#modal-agregar-dano");
        let caso_id = $('#caso_id').val();
        let dano_id = $('#caso_dano_territorio_dano_id').val();
        let territorio_id = $('#caso_dano_territorio_territorio_id').val();
        let descripcion = $('#caso_dano_territorio_descripcion').val();
        
        let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/agregar_dano/'; ?>";    

        let datos = {
                    "caso_id" : caso_id,
                    "dano_id" : dano_id,
                    "territorio_id" : territorio_id,
                    "descripcion" : descripcion
                    };

        $.ajax(url, {
            data: datos,
            method: 'POST',
            success: function (data, textStatus, jqXHR) {  
                $("#div_gestion_danos").html(data);
                btn.button('reset');
                modal.modal('hide');
                $("#btn-cancelar-agregar-dano").prop('disabled', false); 
                
                $('#caso_dano_territorio_descripcion').val('');
                $('#caso_dano_territorio_territorio_id').val('');
                $('#caso_dano_territorio_dano_id').val('');
                $('#caso_dano_territorio_tipo_dano_id').val('');                  
                $("#alert-id-guardar-dano").show();
                $("#alert-id-guardar-dano").hide().fadeIn(500).delay(4000).fadeOut(500);                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('ERROR en agregarDano()');
                btn.button('reset');
            }
        });
    }
        
        function setVariablesEliminar(caso_dano_territorio_id_) {
            caso_dano_territorio_id = caso_dano_territorio_id_;        
        }
        
        function eliminarCasoDanoTerritorio(){
            let caso_id = $('#caso_id').val();
            $("#btn-cancelar-eliminar-dano").hide();
            let btn = $('#btn-eliminar-dano');
            btn.button('loading');
            let modal = $("#modal_eliminar_dano");
            //let nombre_dano = $("#dano_nombre").val();
            let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/eliminar_dano/'; ?>";    

            let datos = {
                        "caso_id" : caso_id,
                        "caso_dano_territorio_id" : caso_dano_territorio_id
                        };

            $.ajax(url, {
                data: datos,
                method: 'POST',
                success: function (data, textStatus, jqXHR) {  
                    $("#div_gestion_danos").html(data);
                    btn.button('reset');
                    modal.modal('hide');
                    $("#btn-cancelar-eliminar-dano").show();
                    $("#alert-id-eliminar").show();
                    $("#alert-id-eliminar").hide().fadeIn(500).delay(4000).fadeOut(500);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#btn-cancelar-eliminar-dano").show();
                    alert('ERROR en eliminarDano()');
                    btn.button('reset');
                }
            });
        }
        
         function cargarModalEditarCasoDanoTerritorio(caso_dano_territorio_id){
            //let caso_id = $('#caso_id').val();
            //$("#btn-cancelar-eliminar-dano").hide();
            //let btn = $('#btn-eliminar-dano');
            //btn.button('loading');
            //let modal = $("#modal_eliminar_dano");
            //let nombre_dano = $("#dano_nombre").val();
            let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/cargar_editar_dano/'; ?>";    

            let datos = {
                        "caso_dano_territorio_id" : caso_dano_territorio_id
                        };

            $.ajax(url, {
                data: datos,
                method: 'POST',
                success: function (data, textStatus, jqXHR) {  
                    $("#div_modal_editar").html(data);
                    let modal = $("#modal-editar-dano");
                    //btn.button('reset');
                    modal.modal('show');
//                    $("#btn-cancelar-eliminar-dano").show();
//                    $("#alert-id-eliminar").show();
//                    $("#alert-id-eliminar").hide().fadeIn(500).delay(4000).fadeOut(500);
                },
                error: function (jqXHR, textStatus, errorThrown) {
//                    $("#btn-cancelar-eliminar-dano").show();
                    alert('ERROR en cargarModalEditarCasoDanoTerritorio()');
//                    btn.button('reset');
                }
            });
        }
        
        function validarBotonEditarDano(){
            var territorio_id = $('#editar_caso_dano_territorio_territorio_id').val();
            var tipo_dano_id = $('#editar_caso_dano_territorio_tipo_dano_id').val();
            var dano_id = $('#editar_caso_dano_territorio_dano_id').val();
            var descripcion = $('#editar_caso_dano_territorio_descripcion').val();
            
            if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                $("#btn-guardar-cambio-dano").prop('disabled', false);
            }else{
                $("#btn-guardar-cambio-dano").prop('disabled', true);
            }
            
        }
        
        function onChangeTipoDanoEditar(){
                  
            var tipo_dano_id = $('#editar_caso_dano_territorio_tipo_dano_id').val();
            var datos = {
                "tipo_dano_id" : tipo_dano_id
            };
            var url = "<?php echo PUBLIC_PATH . 'observatorio/genericos/db_select_danos_editar/'; ?>";
            
            $.ajax(url, {
                data: datos,
                method: 'POST',
                success: function (data, textStatus, jqXHR) {  
                    $("#div_select_dano_editar").html(data);
                    //let modal = $("#modal-editar-dano");
                    $("#div_select_dano_editar").html(data);
                    $("#editar_caso_dano_territorio_dano_id").focus();  
                    
                    var territorio_id = $('#editar_caso_dano_territorio_territorio_id').val();
                    var tipo_dano_id = $('#editar_caso_dano_territorio_tipo_dano_id').val();
                    var dano_id = $('#editar_caso_dano_territorio_dano_id').val();
                    var descripcion = $('#editar_caso_dano_territorio_descripcion').val();  
                    if(territorio_id !== '' && dano_id !== '' && descripcion !== '' && tipo_dano_id !== ''){
                        $("#btn-guardar-cambio-dano").prop('disabled', false);
                    }else{
                        $("#btn-guardar-cambio-dano").prop('disabled', true);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert('ERROR en cargarDano');
                }
            });
        }
        
        function guardarCambiosDano() {
        $("#btn-cancelar-guardar-cambio-dano").prop('disabled', true);
        let btn = $('#btn-guardar-cambio-dano');
        btn.button('loading');
        let modal = $("#modal-editar-dano");
        let caso_id = $('#caso_id').val();
        let caso_dano_territorio_id = $('#caso_dano_territorio_id').val();
        let dano_id = $('#editar_caso_dano_territorio_dano_id').val();
        let territorio_id = $('#editar_caso_dano_territorio_territorio_id').val();
        let descripcion = $('#editar_caso_dano_territorio_descripcion').val();
        
        let url = "<?php echo PUBLIC_PATH . 'dano/gestion_danos/guardar_cambios_dano/'; ?>";    

        let datos = {
                    "caso_id" : caso_id,
                    "caso_dano_territorio_id" : caso_dano_territorio_id,
                    "dano_id" : dano_id,
                    "territorio_id" : territorio_id,
                    "descripcion" : descripcion
                    };

        $.ajax(url, {
            data: datos,
            method: 'POST',
            success: function (data, textStatus, jqXHR) {  
                $("#div_gestion_danos").html(data);
                btn.button('reset');
                modal.modal('hide');
                $("#btn-cancelar-guardar-cambio-dano").prop('disabled', false); 
                
//                $('#caso_dano_territorio_descripcion').val('');
//                $('#caso_dano_territorio_territorio_id').val('');
//                $('#caso_dano_territorio_dano_id').val('');
//                $('#caso_dano_territorio_tipo_dano_id').val('');                  
                $("#alert-id-guardar-cambio-dano").show();
                $("#alert-id-guardar-cambio-dano").hide().fadeIn(500).delay(4000).fadeOut(500);                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('ERROR en guardarCambiosDano()');
                btn.button('reset');
            }
        });
    }
    
        /* });*/
        
</script>