<?php View::flash(); ?>

<div class="container shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>        
        <div class="row">
            <div class="col-md-12">
                <label for="panel_info_basica"><h3 class="panel-title">Seleccione los actores armados</h3></label>                
               <div id="panel_info_basica" class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-md-12">
                            <?php echo DwForm::dbCheck('actor_armado','nombre',array('opcion/presunto_responsable','getListadoPresuntoResponsableDBS',''),NULL, $array_actor_armado); ?>
                        </div>
                    </div>                                       
                </div>
               </div>
            </div>
    
    <div class="row">
        <div class="col-md-12">               
            <label for="panel_fuente"><h3 class="panel-title">Fuente(s) de la información</h3></label>               
              <div id="panel_fuente" class="panel panel-default">
                  <div class="panel-body">
                    <?php View::partial('fuentes/editar', false, 
                            array('fuentes'=>$fuentes, 'tabla'=>'actor_armado', 'tabla_identi'=>$obj_territorio->id)); ?> 
                 </div>                    
             </div>
        </div> 
    </div>
          
                    
                             

        <div class="row">
            <div class="form-actions">                   
                <?php echo DwForm::send('Actualizar'); ?>
                <?php echo DwForm::cancel($url_redir_back); ?>
                
            </div>
        </div>

    <?php echo DwForm::close(); ?> 
    
</div>